services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    networks:
      - cloud_1
    volumes:
      - db_data:/var/lib/mysql
  
  wordpress:
    image: wordpress:latest
    restart: always
    env_file: .env
    networks:
      - cloud_1
    ports:
      - 8080:80
    depends_on:
      - db

networks:
  cloud_1:

volumes:
  db_data:
